### ISSUE TITLE
dependency resolution failiure with latest mist and wisp

### ISSUE THREAD

**Issue by jmrflora** [ghivert/cors-builder#2]
when adding cors_builder to a new wisp project an error occurs.

Unable to find compatible versions for the version constraints in your
gleam.toml. The conflicting packages are:

- mist
- server // my project
- wisp
- cors_builder

I think you already know about this but figured i might just post here.

**Comment by ghivert** [comment]
Hi! Thanks for raising this. Could you indicate the versions you're using and your gleam version? 🙂

**Comment by jmrflora** [comment]
In the project that i am using right know, the versions kinda resolved themselves, but the error can be reproduced by creating a new project, adding wisp and then trying to add cors_builder.

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
wisp = ">= 1.1.0 and < 2.0.0"

❯ gleam add cors_builder
  Resolving versions
error: Dependency resolution failed

An error occurred while determining what dependency packages and
versions should be downloaded.
The error from the version resolver library was:

Unable to find compatible versions for the version constraints in your
gleam.toml. The conflicting packages are:

- cors_builder
- mist
- server

gleam version: gleam 1.4.1

**Comment by ghivert** [comment]
Thanks! Fixed 🙂 Feel free to reopen if the issue is still there!
